VillaWebUI/Controllers/AcountController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Text;
using Villa.DTO.Dtos.IdentityDtos;
using Villa.Entity.Entities;

namespace VillaWebUI.Controllers
{
	public class AcountController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;

        public AcountController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager = null)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Register()
		{
			return View();
		}
		[HttpPost]	
		public async Task<IActionResult> Register(RegisterDto registerDto)
		{
			var user = new ApplicationUser()
			{
				NameSurname=registerDto.Namesurname,
				Email = registerDto.Email,
				UserName=registerDto.Username
			};
			var result= await _userManager.CreateAsync(user,registerDto.Password);	
			if (!result.Succeeded)
			{
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("",item.Description);
                }
				return View();
            }
			return RedirectToAction("Login");
		}
		public IActionResult Login()
		{
			return View();
		}

		[HttpPost]	
		public async Task<IActionResult> Login(LoginDto loginDto)
		{
			var user = await _userManager.FindByNameAsync(loginDto.Username);
			if (user==null)
			{
				ModelState.AddModelError("","Kullanıcı Adı Veya Şifre Hatalı");
				return View();
			}
			var result = await _signInManager.CheckPasswordSignInAsync(user, loginDto.Password,false);
			if (!result.Succeeded) {

				ModelState.AddModelError("","Kullanıcı adı veya Şifre Hatalı");
				return View();
			}
			return RedirectToAction("Index","Banner");	
			
		}
	}
}

VillaWebUI/Views/Acount/Login.cshtml
@model LoginDto
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="~/colorlib-regform-7/fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="~/colorlib-regform-7/css/style.css">
</head>
<body>

    <div class="main">

        <!-- Sign up form kayıt ol -->
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="~/colorlib-regform-7/images/signin-image.jpg" alt="sing up image"></figure>
                        <a href="Register" class="signup-image-link">Hesap Oluştur</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="login-form" asp-controller="Acount" asp-action="Login">
                            <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" asp-for="Username" id="your_name" placeholder="Kullanıcı adı" />
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" asp-for="Password" id="your_pass" placeholder="Şifre" />
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Bnei Hatırla</label>
                            </div>
                            <p style="color:red" >@Html.ValidationSummary()</p>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Giriş yap" />
                            </div>
                        </form>
                    
                    </div>
                </div>
            </div>
        </section>


    </div>

    <!-- JS -->
    <script src="~/colorlib-regform-7/vendor/jquery/jquery.min.js"></script>
    <script src="~/colorlib-regform-7/js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

VillaWebUI/Views/Acount/Register.cshtml
@model RegisterDto
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="~/colorlib-regform-7/fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="~/colorlib-regform-7/css/style.css">
</head>
<body>

    <div class="main">

        <!-- Sign up form kayıt ol -->
         <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Kaydol</h2>
                        <form method="POST" class="register-form" id="register-form" asp-controller="Acount" asp-action="Register">
                            <div class="form-group">
                                <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" asp-for="Namesurname" id="name" placeholder="İsim Soyisim" />
                            </div>
                            <div class="form-group">
                                <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" asp-for="Username" id="name" placeholder="Kullanıcı Adı" />
                            </div>
                            <div class="form-group">
                                <label for="email"><i class="zmdi zmdi-email"></i></label>
                                <input type="email" asp-for="Email" id="email" placeholder="Email" />
                            </div>
                            <div class="form-group">
                                <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" asp-for="Password" id="pass" placeholder="Şifre" />
                            </div>
                            <div class="form-group">
                                <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                                <input type="password" asp-for="Password" id="re_pass" placeholder="Şifreyi Tekrar Girin" />
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                                <label for="agree-term" class="label-agree-term"><span><span></span></span>Tümünü Onaylıyorum<a href="#" class="term-service">Hizmet Şartları</a></label>
                            </div>
                            <p style="color:red">@Html.ValidationSummary()</p>
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register" />
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="~/colorlib-regform-7/images/signup-image.jpg" alt="sing up image"></figure>
                        <a href="/Acount/login" class="signup-image-link">Zaten Üyeyim. Giriş Yap</a>
                    </div>
                </div>
            </div>
        </section> 

     

    </div>

    <!-- JS -->
    <script src="~/colorlib-regform-7/vendor/jquery/jquery.min.js"></script>
    <script src="~/colorlib-regform-7/js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->  
</html>