VillaWebUI/Controllers/CounterController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Villa.Business.Abstract;
using Villa.DTO.Dtos.ContactDtos;
using Villa.DTO.Dtos.CounterDtos;
using Villa.Entity.Entities;

namespace VillaWebUI.Controllers
{
    public class CounterController : Controller
    {
        private readonly ICounterSerivce _counterSerivce;
        private readonly IMapper _mapper;
        public CounterController(ICounterSerivce counterSerivce, IMapper mapper)
        {
            _counterSerivce = counterSerivce;
            _mapper = mapper;
        }


        public async Task<IActionResult> Index()
        {
            var values = await _counterSerivce.TGetListAsnc();
            var counterList = _mapper.Map<List<ResultCounterDto>>(values);
            return View(counterList);
        }
        public async Task<IActionResult> DeleteCounter(ObjectId id)
        {
            await _counterSerivce.TDelete(id);
            return RedirectToAction("Index");

        }
        public IActionResult CreateCounter()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateCounter(CreateCounterDto createCounterDto)
        {
            var newCounter = _mapper.Map<Counter>(createCounterDto);
            await _counterSerivce.TCreateAsync(newCounter);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateCounter(ObjectId id)
        {
            var value = await _counterSerivce.TGetByIdAsync(id);
            var counter = _mapper.Map<UpdateCounterDto>(value);
            return View(counter);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateCounter(UpdateCounterDto updateCounterDto)
        {

            var counter = _mapper.Map<Counter>(updateCounterDto);
            await _counterSerivce.TUpdateAsync(counter);
            return RedirectToAction("Index");

        }
    }
}

VillaWebUI/Views/Counter/CreateCounter.cshtml
@model ResultCounterDto
@{
    ViewData["Title"] = "Sayaç Oluştur";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form method="post">
 
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Sayaç</label>
    <input type="text" asp-for="Count" class="form-control" />
    <br />
    <button class="btn btn-outline-dark">Kaydet</button>

</form>

VillaWebUI/Views/Counter/Index.cshtml
@model List<ResultCounterDto>
@{
    ViewData["Title"] = "Sayaç Listesi";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-hover table-bordered">
    @{
        int count = 0;
    };
    <tr>
        <th>#</th>
        <th>Başlık</th>
        <th>Sayaç</th>
        

    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td>@item.Title</td>
            <td>@item.Count</td>
            <td>
                <a asp-controller="Counter" asp-action="DeleteCounter" asp-route-id="@item.Id" class="btn btn-outline-danger">Sil</a>
                <a asp-controller="Counter" asp-action="UpdateCounter" asp-route-id="@item.Id" class="btn btn-outline-info">Güncelle</a>
            </td>
        </tr>

    }
</table>
<a asp-controller="Counter" asp-action="CreateCounter" class="btn btn-outline-danger">Yeni Banner Ekle</a>

VillaWebUI/Views/Counter/UpdateCounter.cshtml
@model UpdateCounterDto
@{
    ViewData["Title"] = "Sayaç Güncelle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form method="post">
    <input type="hidden" asp-asp-for="Id"></input>
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Sayaç</label>
    <input type="text" asp-for="Count" class="form-control" />
    <br />
  
    <button class="btn btn-outline-dark">Güncelle</button>

</form>