VillaWebUI/Controllers/SubHeaderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Villa.Business.Abstract;
using Villa.DTO.Dtos.SubHeaderDtos;
using Villa.Entity.Entities;

namespace VillaWebUI.Controllers
{
    public class SubHeaderController : Controller
    {
        private readonly ISubHeaderService _subHeaderService;
        private readonly IMapper _mapper;

        public SubHeaderController(ISubHeaderService subHeaderService, IMapper mapper)
        {
            _subHeaderService = subHeaderService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var values = await _subHeaderService.TGetListAsnc();
            var SubHeaderList = _mapper.Map<List<ResultSubHeaderDto>>(values);
            return View(SubHeaderList);
        }
        public async Task<IActionResult> DeleteSubHeader(ObjectId id)
        {
            await _subHeaderService.TDelete(id);
            return RedirectToAction("Index");
        }
        public IActionResult CreateSubHeader()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateSubHeader(CreateSubHeaderDto createSubHeaderDto)
        {
            var newSubHeader = _mapper.Map<SubHeader>(createSubHeaderDto);
            await _subHeaderService.TCreateAsync(newSubHeader);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> UpdateSubHeader(ObjectId id)
        {
            var value = await _subHeaderService.TGetByIdAsync(id);
            var updateSubHeader = _mapper.Map<UpdateSubHeaderDto>(value);
            return View(updateSubHeader);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSubHeader(UpdateSubHeaderDto updateSubHeaderDto)
        {
            var product = _mapper.Map<SubHeader>(updateSubHeaderDto);
            await _subHeaderService.TUpdateAsync(product);
            return RedirectToAction("Index");
        }
    }
}

VillaWebUI/Views/SubHeader/CreateSubHeader.cshtml
@model CreateSubHeaderDto
@{
    ViewData["Title"] = "CreateSubHeader";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form method="post">
    <label>Adres</label>
    <input type="text" asp-for="Address" class="form-control" />
    <br />
    <label>Email</label>
    <input type="text" asp-for="Email" class="form-control" />
    <br />
    <label>Faceook-Link</label>
    <input type="text" asp-for="Facebook" class="form-control" />
    <br />
    <label>Twitter-Link</label>
    <input type="text" asp-for="Twitter" class="form-control" />
    <br />
    <label>Linkedin-Link</label>
    <input type="text" asp-for="Linkedin" class="form-control" />
    <br />
    <label>Instagram-link</label>
    <input type="text" asp-for="Instagram" class="form-control" />
    <br />
    <button class="btn btn-outline-dark">Kaydet</button>
</form>

VillaWebUI/Views/SubHeader/Index.cshtml
@model List<ResultSubHeaderDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-hover table-bordered">
    @{
        int count = 0;
    };
    <tr>
        <th>#</th>
        <th>Address</th>
        <th>Email</th>
        <th>Facebook</th>
        <th>Twitter</th>
        <th>Linkedin</th>
        <th>Instagram</th>
    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td>@item.Address</td>
            <td>@item.Email</td>
            <td><a href="@item.Facebook" target="_blank">Facebook</a></td>
            <td><a href="@item.Twitter" target="_blank">Twitter</a></td>
            <td><a href="@item.Linkedin" target="_blank">Linkedin</a></td>
            <td><a href="@item.Instagram" target="_blank">Instagram</a></td>
            <td>
                <a asp-controller="SubHeader" asp-action="DeleteSubHeader" asp-route-id="@item.Id" class="btn btn-outline-danger">Sil</a>
                <a asp-controller="SubHeader" asp-action="UpdateSubHeader" asp-route-id="@item.Id" class="btn btn-dark">Güncelle</a>
            </td>
        </tr>

    }
</table>
<a asp-controller="SubHeader" asp-action="CreateSubHeader" class="btn btn-outline-danger">Yeni SubHeader Ekle</a>

VillaWebUI/Views/SubHeader/UpdateSubHeader.cshtml
@model UpdateSubHeaderDto
@{
    ViewData["Title"] = "UpdateSubHeader";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form method="post">
    <input type="hidden" asp-for="Id"></input>
    <label>Adres</label>
    <input type="text" asp-for="Address" class="form-control" />
    <br />
    <label>Email</label>
    <input type="text" asp-for="Email" class="form-control" />
    <br />
    <label>Faceook-Link</label>
    <input type="text" asp-for="Facebook" class="form-control" />
    <br />
    <label>Twitter-Link</label>
    <input type="text" asp-for="Twitter" class="form-control" />
    <br />
    <label>Linkedin-Link</label>
    <input type="text" asp-for="Linkedin" class="form-control" />
    <br />
    <label>Instagram-link</label>
    <input type="text" asp-for="Instagram" class="form-control" />
    <br />
    <button class="btn btn-outline-dark">Kaydet</button>
</form>