VillaWebUI/Controllers/FeatureController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Villa.Business.Abstract;
using Villa.DTO.Dtos.BannerDtos;
using Villa.DTO.Dtos.FeatureDtos;
using Villa.Entity.Entities;

namespace VillaWebUI.Controllers
{
    
   
    public class FeatureController : Controller
    {
        private readonly IFeatureSerivce _featureSerivce;
        private readonly IMapper _mapper;
        public FeatureController(IFeatureSerivce featureSerivce, IMapper mapper)
        {
            _featureSerivce = featureSerivce;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _featureSerivce.TGetListAsnc();
            var featureList = _mapper.Map<List<ResultFeatureDto>>(values);
            return View(featureList);
        }
        public async Task<IActionResult> DeleteFeature(ObjectId id)
        {
            await _featureSerivce.TDelete(id);
            return RedirectToAction("Index");
        }
        public IActionResult CreateFeature()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateFeature(CreateFeatureDto createFeatureDto)
        {
            var newFeature = _mapper.Map<Feature>(createFeatureDto);
            await _featureSerivce.TCreateAsync(newFeature);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> UpdateFeature(ObjectId id)
        {
            var value = await _featureSerivce.TGetByIdAsync(id);
            var updateFeature = _mapper.Map<UpdateFeatureDto>(value);
            return View(updateFeature);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFeature(UpdateFeatureDto updateFeatureDto)
        {
            var feature = _mapper.Map<Feature>(updateFeatureDto);
            await _featureSerivce.TUpdateAsync(feature);
            return RedirectToAction("Index");
        }
    }
}

VillaWebUI/Views/Feature/CreateFeature.cshtml
@model CreateFeatureDto
@{
    ViewData["Title"] = "Öne Çıkarılan Oluştur";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form method="post">
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Alt-Başlık</label>
    <input type="text" asp-for="SubTitle" class="form-control" />
    <br />
    <label>Fotoğraf-Linki</label>
    <input type="text" asp-for="ImageUrl" class="form-control" />
    <br />
    <label>Metrekare</label>
    <input type="text" asp-for="Square" class="form-control" />
    <br />
    <label>Kontrat Türü</label>
    <input type="text" asp-for="Contract" class="form-control" />
    <br />
    <label>Ödeme Türü</label>
    <input type="text" asp-for="Payment" class="form-control" />
    <br />
    <label>Güvenlik</label>
    <input type="text" asp-for="Safety" class="form-control" />
    <br />
    <button class="btn btn-outline-dark">Kaydet</button>
</form>

VillaWebUI/Views/Feature/Index.cshtml
@model List<ResultFeatureDto>
@{
    ViewData["Title"] = "Öne Çıkarılanar ";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<table class="table table-hover table-bordered">
    @{
        int count = 0;
    };
    <tr>
        <th>#</th>
        <th>Başlık</th>
        <th>Alt-Başlık</th>
        <th>Image-Url</th>
        <th>Metrekare</th>
        <th>Kontrat Türü</th>
        <th>Ödeme Türü</th>
        <th>Güvenlik</th>
       



    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td>@item.Title</td>
            <td>@item.SubTitle</td>
            <td>@item.ImageUrl</td>
            <td>@item.Square</td>
            <td>@item.Contract</td>
            <td>@item.Payment</td>
            <td>@item.Safety</td>
           

            <td>
                <a asp-controller="Feature" asp-action="DeleteFeature" asp-route-id="@item.Id" class="btn btn-outline-danger">Sil</a>
                <a asp-controller="Feature" asp-action="UpdateFeature" asp-route-id="@item.Id" class="btn btn-outline-info">Güncelle</a>
            </td>
        </tr>

    }
</table>
<a asp-controller="Feature" asp-action="CreateFeature" class="btn btn-outline-danger">Yeni Öne-Çıkarılan Ekle</a>

VillaWebUI/Views/Feature/UpdateFeature.cshtml
@model UpdateFeatureDto
@{
    ViewData["Title"] = "Öne Çıkarılan Güncelle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form method="post">
    <input type="hidden" asp-asp-for="Id"></input> 
    <label>Başlık</label>
    <input type="text" asp-for="Title" class="form-control" />
    <br />
    <label>Alt-Başlık</label>
    <input type="text" asp-for="SubTitle" class="form-control" />
    <br />
    <label>Fotoğraf-Linki</label>
    <input type="text" asp-for="ImageUrl" class="form-control" />
    <br />
    <label>Metrekare</label>
    <input type="text" asp-for="Square" class="form-control" />
    <br />
    <label>Kontart Türü</label>
    <input type="text" asp-for="Contract" class="form-control" />
    <br />
    <label>Ödeme Türü</label>
    <input type="text" asp-for="Payment" class="form-control" />
    <br />
    <label>Güvenlik</label>
    <input type="text" asp-for="Safety" class="form-control" />
    <br />
    <button class="btn btn-outline-dark">Kaydet</button>
</form>